# -*- coding: utf-8 -*-
"""Prime Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syi00wOc5bX1_lKXpOTiZlBKe_4jpQqH
"""



# your code goes here
n_cases = int(input())

for y in range(n_cases):
	n,k = raw_input().split()
	n_1 = int(n)
	n_2 = int(k)
	for x in range(n_1, n_2+1):
		if x > 1:
			for i in range(2, x):
				if (x % i) == 0 :
					break
				elif x == i+1:
					print(x)
					break

